# Generated by Django 5.0.6 on 2026-02-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbox', '0002_alter_textbox_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbox',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='textbox',
            name='content',
            field=models.TextField(unique=True),
        ),
    ]
