# Generated by Django 5.0.6 on 2026-02-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbox', '0003_alter_textbox_code_alter_textbox_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbox',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='textbox',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
